"""
Export ERPNext metadata-only bundle for clean environment cloning.

This script exports configuration docs (roles/workspaces/customizations) and
excludes business transactional data (Items, Customers, Sales Invoices, etc.).

Usage:
  python scripts/export_metadata_bundle.py

Optional env vars:
  ERPNEXT_URL
  ERPNEXT_API_KEY
  ERPNEXT_API_SECRET
  METADATA_OUTPUT_DIR
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests

ERPNEXT_URL = os.getenv("ERPNEXT_URL", "http://atlaslakeserp").strip().rstrip("/")
ERPNEXT_API_KEY = os.getenv("ERPNEXT_API_KEY", "")
ERPNEXT_API_SECRET = os.getenv("ERPNEXT_API_SECRET", "")
OUTPUT_ROOT = Path(os.getenv("METADATA_OUTPUT_DIR", "artifacts/metadata")).resolve()

DOCTYPES_TO_EXPORT = [
    "Role",
    "Role Profile",
    "Module Profile",
    "Workspace",
    "Custom Field",
    "Property Setter",
    "Print Format",
    "Notification",
    "Client Script",
    "Server Script",
]

# Fields generated by ERPNext at runtime that should not be imported directly.
DROP_FIELDS = {
    "creation",
    "modified",
    "modified_by",
    "owner",
    "docstatus",
    "idx",
    "_user_tags",
    "_comments",
    "_assign",
    "_liked_by",
}


class ERPClient:
    def __init__(self, base_url: str, api_key: str, api_secret: str) -> None:
        if not api_key or not api_secret:
            raise ValueError("ERPNEXT_API_KEY and ERPNEXT_API_SECRET are required")
        self.base_url = base_url
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"token {api_key}:{api_secret}",
                "Content-Type": "application/json",
            }
        )
        self.session.verify = False

    def _url(self, path: str) -> str:
        return f"{self.base_url}{path}"

    def ping(self) -> None:
        r = self.session.get(self._url("/api/method/ping"), timeout=20)
        r.raise_for_status()
        if r.json().get("message") != "pong":
            raise RuntimeError(f"Unexpected ping response: {r.text[:200]}")

    def list_names(self, doctype: str) -> list[str]:
        names: list[str] = []
        start = 0
        page_size = 500
        while True:
            params = {
                "fields": json.dumps(["name"]),
                "limit_start": start,
                "limit_page_length": page_size,
                "order_by": "modified desc",
            }
            r = self.session.get(self._url(f"/api/resource/{doctype}"), params=params, timeout=60)
            r.raise_for_status()
            rows = r.json().get("data", [])
            if not rows:
                break
            names.extend([row["name"] for row in rows if "name" in row])
            if len(rows) < page_size:
                break
            start += page_size
        return names

    def get_doc(self, doctype: str, name: str) -> dict[str, Any]:
        r = self.session.get(
            self._url(f"/api/resource/{doctype}/{requests.utils.quote(name)}"),
            timeout=60,
        )
        r.raise_for_status()
        return r.json().get("data", {})


def scrub_doc(value: Any) -> Any:
    if isinstance(value, dict):
        cleaned = {}
        for key, item in value.items():
            if key in DROP_FIELDS:
                continue
            cleaned[key] = scrub_doc(item)
        return cleaned
    if isinstance(value, list):
        return [scrub_doc(item) for item in value]
    return value


def main() -> None:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_file = OUTPUT_ROOT / f"metadata-bundle-{timestamp}.json"

    client = ERPClient(ERPNEXT_URL, ERPNEXT_API_KEY, ERPNEXT_API_SECRET)
    client.ping()

    bundle: dict[str, Any] = {
        "exported_at_utc": timestamp,
        "source_url": ERPNEXT_URL,
        "doctypes": {},
    }

    for doctype in DOCTYPES_TO_EXPORT:
        print(f"Exporting {doctype} ...")
        docs: list[dict[str, Any]] = []
        for name in client.list_names(doctype):
            try:
                doc = client.get_doc(doctype, name)
                docs.append(scrub_doc(doc))
            except Exception as exc:
                print(f"- Skipped {doctype}/{name}: {exc}")
        bundle["doctypes"][doctype] = docs
        print(f"- {doctype}: {len(docs)} docs")

    out_file.write_text(json.dumps(bundle, indent=2, ensure_ascii=True), encoding="utf-8")
    print(f"\nMetadata bundle written: {out_file}")


if __name__ == "__main__":
    main()
